restructure with data taken from PELUX
Pelagicore/software-factory-blueprint pull request #10
Opened 2017-09-06 07:01 UTC by tobsan

Note: Once this gets merged, the idea is to do a PR for the PELUX Software Factory to make use of this new structure.

Also describes the idea of the blueprint and that it should be used with
a deployment so that it is clear why it may not seem useful.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2017-09-06 07:17 UTC, tobsan commented
Structure of articles is not final but will probably change, but it is a start at least.

2017-09-06 10:23 UTC, rpannek approved these changes

2017-09-06 10:38 UTC, breakreturn requested changes
Nice. Have some comments on the generic "this is the Blueprint" texts.

2017-09-06 10:38 UTC, breakreturn commented on docs/articles/baseplatform/index.rst
> +.. .. include:: prerequisites.rst
Why are these left in here?

2017-09-06 10:38 UTC, breakreturn commented on docs/articles/intro/index.rst
> +from whichever git contains the project-specific Software Factory. Our reference deployment *PELUX*
The reference Deployment is "PELUX Baseline SWF Deployment"

2017-09-06 10:38 UTC, breakreturn commented on docs/articles/intro/index.rst
> +.. only:: blueprint
I don't like this. Could we write the content in general as  "the blueprint" and not "this blueprint" and assume that the blueprint is something that co-exists with a Deployment at most times. The few that reads the Blueprint in isolation should have gotten the description of the structure as part of the Blueprint anyway and will know that there is a Deployment missing.

The section that describes the structure to the reader, including nomenclature etc, doesn't need to be part of this change, but this change could assume there will be that kind of info later.

2017-09-06 10:38 UTC, breakreturn commented on docs/articles/intro/index.rst
> +A nice way of using this blueprint in a project-specific setting is to use it as a *git submodule*
In general I think we should write how to do this, not recommend one way of doing it. The difference is often small, but the docs need to read consistently throughout, and this is the manual of how to actually do things. When a rationale of why we don something in a specific way or when it's relevant to compare different approaches that could be separated from the other text.

2017-09-06 11:47 UTC, tobsan commented on docs/articles/baseplatform/index.rst
> +.. .. include:: prerequisites.rst
Oops, my bad!

2017-09-06 12:27 UTC, tobsan commented
@breakreturn updated after your comments.

2017-09-07 10:55 UTC, breakreturn commented on docs/articles/intro/index.rst
> +Deployment* does exactly that.
Why not link now already? We have the Baseline Deployment available publicly.

2017-09-07 11:10 UTC, merged