Fix structure, table of contents errors, minor code line errors
Pelagicore/software-factory-blueprint pull request #131
Opened 2018-07-10 14:58 UTC by fhajredini

2018-07-10 15:44 UTC, sashko requested changes
title

2018-07-10 15:45 UTC, sashko requested changes

2018-07-10 15:45 UTC, sashko commented on docs/articles/architecture/arch-intro.rst
> +- The :ref:`arch-layers` presents the layers used in pelux.
not layer?

2018-07-12 08:05 UTC, fhajredini commented on docs/articles/architecture/arch-intro.rst
> +- The :ref:`arch-layers` presents the layers used in pelux.
Afaik, layers.

2018-07-12 11:47 UTC, FlorentRevest approved these changes

2018-07-12 12:03 UTC, sashko approved these changes

2018-07-12 12:04 UTC, TSAnsari commented on docs/articles/architecture/arch-layers.rst
>  =======================================
Aligned '=' with 't' in 'project' on above line

2018-07-12 12:19 UTC, TSAnsari approved these changes
Just fix the comment and I am ok.

2018-07-12 12:31 UTC, merged