add update
Pelagicore/software-factory-blueprint pull request #138
Opened 2018-10-11 07:44 UTC by vsydiakin

Signed-off-by: root <root@localhost.localdomain>

2018-10-11 07:58 UTC, frznlogic commented
First off, the commit message needs to be improved ;)
http://ntg-x.projects.luxoft.com/software-factory/chapters/ways-of-working/git/good-commits.html

Second, your signed off by line is set to root@localhost.localdomain. Please configure the git client properly. 
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

2018-10-11 10:48 UTC, sashko requested changes
Describe the change and fix sign off, please.

2018-10-11 12:03 UTC, rpannek approved these changes

2018-10-18 11:46 UTC, thenor requested changes
As already commented we need a description of the change (change the commit message to be more descriptive) and the sign-off needs to be aligned with your name and e-mail.

2018-10-22 14:01 UTC, thenor commented on docs/articles/infrastructure/ci-cd/jenkins.rst
> +#   ExecStartPre=-/usr/bin/docker rm %n
This line should be indented so that this is correctly generated as a code block.

```suggestion
    #   ExecStartPre=-/usr/bin/docker rm %n
```

2018-10-23 06:27 UTC, sashko commented
@thenor did you mean to squash them?

2018-10-23 08:08 UTC, thenor commented
@sashko Did I do something? In that case I apologize. I used a function in GitHub where I could suggest a code change. I don't think I changed the code.

2018-10-23 08:09 UTC, sashko commented
@thenor ah, I see now. It looks like you've updated the PR with adding a new commit.

2018-10-23 08:11 UTC, thenor commented
The old commit with the incorrect sign-off is still present, so that needs to be removed before I will accept this Pull Request.

2018-10-23 08:29 UTC, DunderRoffe commented
Me and @vsydiakin are working in combinding our efforts to one pr

2018-10-23 11:21 UTC, DunderRoffe commented
Closing this and reopening one from another remote

2018-10-23 11:21 UTC, closed without merging

2018-10-23 11:22 UTC, DunderRoffe commented
https://github.com/Pelagicore/software-factory-blueprint/pull/141