Add article on using bootchart2
Pelagicore/software-factory-blueprint pull request #154
Opened 2019-02-21 16:02 UTC by sashko

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

2019-02-28 15:16 UTC, JEderonn commented on docs/articles/baseplatform/measuring-startup-performance-with-systemd-analyze.rst
> +`systemd` provides a tool called `systemd-analyze` that can be used to retreive statistics
s/retreive/retrieve

2019-02-28 15:19 UTC, JEderonn reviewed
Minor typo, please fix before merge

2019-02-28 15:20 UTC, sashko commented on docs/articles/baseplatform/measuring-startup-performance-with-systemd-analyze.rst
> +`systemd` provides a tool called `systemd-analyze` that can be used to retreive statistics
done

2019-03-01 09:00 UTC, thenor commented on docs/articles/baseplatform/measuring-startup-performance-with-systemd-analyze.rst
> +To retreive statistics information from systemd, simply run:
```suggestion
To retrieve statistics information from systemd, run:
```

2019-03-01 09:01 UTC, thenor requested changes
Minor nit-picky comments.

2019-03-01 09:07 UTC, sashko commented on docs/articles/baseplatform/measuring-startup-performance-with-systemd-analyze.rst
> +To retreive statistics information from systemd, simply run:
done

2019-03-01 12:19 UTC, thenor approved these changes

2019-03-01 14:09 UTC, merged