Fix duplicate label warning
Pelagicore/software-factory-blueprint pull request #35
Opened 2017-10-24 12:40 UTC by demonicblue

Rename included file to .inc. Otherwise the yocto-project-integration
label is seen twice and generates a warning.

Signed-off-by: Henrik Hugo <hhugo@luxoft.com>

2017-10-24 12:42 UTC, demonicblue commented
This PR requires some discussion. Should the same change be applied to all files that are included by the 'include' directive?
Does this impair the ability to use files in a toctree?

2017-10-24 13:54 UTC, tobsan requested changes
I think we have discussed earlier on ways to get around this by using toctree instead of include for most of these things. Could you try that instead?

2017-10-24 14:16 UTC, demonicblue commented
Yes I can but it will change the structuring of the page somewhat.

2017-10-25 09:24 UTC, tobsan approved these changes

2017-10-25 11:10 UTC, breakreturn approved these changes

2017-10-25 11:10 UTC, merged