substitutions: put substitutions in separate files
Pelagicore/software-factory-blueprint pull request #9
Opened 2017-08-31 11:38 UTC by tobsan

This way, both the blueprint project, and any deployment of it, can add
its own substitutions without having to fiddle around in the
configuration files, plus the deployment can use the substitutions from
the blueprint.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2017-08-31 12:51 UTC, GordanM approved these changes

2017-08-31 15:01 UTC, thenor approved these changes

2017-09-01 07:56 UTC, rpannek requested changes
In this version it is not clear to me how I'm supposed to use it.

2017-09-04 08:57 UTC, tobsan commented
@rpannek Updated with usage example

2017-09-05 13:46 UTC, breakreturn approved these changes

2017-09-05 14:08 UTC, rpannek approved these changes

2017-09-05 14:10 UTC, merged