booting-qemu-image: Add static ip configuration
Pelagicore/software-factory-blueprint pull request #91
Opened 2018-02-12 16:22 UTC by BassemMohsen

2018-02-13 06:38 UTC, mardy requested changes

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +Port forwarding configuration:
I would remove all the ":" at the end of the section titles

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +QEMU emulator can be launched with a serial console support and port forwarding
s/a //

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +Static IP address facilitates more network services for development and
"A static IP address facilitates development of automation and testing scripts."

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +The next commands assumes target ip address is ``192.168.7.2`` and host machine
s/is //

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +      --append "vga=0 uvesafb.mode_option=1280×720-32 root=/dev/hda console=ttyS0 rw mem=512M oprofile.timer=1 ip=192.168.7.2::192.168.7.1:255.255.255.0" -serial stdio
s/--append/-append/

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +   sudo ip address add 192.168.7.1/24 broadcast 192.168.7.255 dev tap0  \
Do you really need the "\\" at the end of the line?

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +3. (Optional) To enable the tap device to access internet.
"...access internet run..." (without breaking the sentence)

2018-02-13 06:38 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +   sudo iptables -A POSTROUTING -t nat -j MASQUERADE -s 192.168.7.1/24; \
Same here, I think you can do without ";" and "\\".

2018-02-14 13:43 UTC, BassemMohsen commented on docs/articles/baseplatform/booting-qemu-image.rst
> +The next commands assumes target ip address is ``192.168.7.2`` and host machine
"is" actually here makes sense

2018-02-14 13:52 UTC, mardy requested changes

2018-02-14 13:52 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +The next commands assumes target ip address is ``192.168.7.2`` and host machine
s/assumes/assume/

2018-02-14 13:52 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +command on the host machine:
s/command/commands/

2018-02-14 13:52 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +SSH access via Port forwarding:
You forgot to remove the colon here

2018-02-14 13:52 UTC, mardy commented on docs/articles/baseplatform/booting-qemu-image.rst
> +SSH access via static ip:
and here

2018-02-19 09:02 UTC, tobsan requested changes

2018-02-19 09:02 UTC, tobsan commented on docs/articles/baseplatform/booting-qemu-image.rst
> +The next commands assumes target ip address is ``192.168.7.2`` and host machine
Can we be more specific when we say "target" and talk about a QEMU target. As a developer, this is confusing, so I assume that a regular user would also be confused by it?

2018-02-19 09:02 UTC, tobsan commented on docs/articles/baseplatform/booting-qemu-image.rst
>      $ ssh root@127.0.0.1 -p 1234
Can we add an explanation for this so that users understand that 1234 map to 22?

2018-02-21 13:32 UTC, mardy approved these changes

2018-02-21 14:15 UTC, tobsan approved these changes

2018-02-21 15:45 UTC, merged